webtalk_init -webtalk_dir /home/jwyngaard/Work/UCT/OneDrive/3096/PracsGit/EEE3096S-2021/WorkPackage6/VivadoProjectWP6/WP6_Vivado.sim/sim_1/behav/xsim/xsim.dir/tb_reg_mem_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Oct 18 10:57:19 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211426657_0_0_701" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9782794c-174b-4702-8a54-69c84f8cd715" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9441ccd9ff12450e91a8e8f4192be805" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Pop" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Pop!_OS 20.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2600.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116952_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2790739273 -regid "211426657_0_0_701" -xml /home/jwyngaard/Work/UCT/OneDrive/3096/PracsGit/EEE3096S-2021/WorkPackage6/VivadoProjectWP6/WP6_Vivado.sim/sim_1/behav/xsim/xsim.dir/tb_reg_mem_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/jwyngaard/Work/UCT/OneDrive/3096/PracsGit/EEE3096S-2021/WorkPackage6/VivadoProjectWP6/WP6_Vivado.sim/sim_1/behav/xsim/xsim.dir/tb_reg_mem_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/jwyngaard/Work/UCT/OneDrive/3096/PracsGit/EEE3096S-2021/WorkPackage6/VivadoProjectWP6/WP6_Vivado.sim/sim_1/behav/xsim/xsim.dir/tb_reg_mem_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
